#!/usr/bin/env python3
"""
Generate boilerplate checks training data.

Reads final_boilerplate_checks.parquet from ../../data and produces
boilerplate_checks.parquet with formatted prompts for training.
"""

import pandas as pd
from transformers import AutoTokenizer


def boilerplatecheck(frame, tokenizer):
    """Format boilerplate check data into training prompts."""
    prompts = []
    for i in range(frame.shape[0]):
        patient_boilerplate = frame.iloc[i].patient_boilerplate_text
        trial_boilerplate = frame.iloc[i].trial_boilerplate_text
        answer = frame.iloc[i].boilerplate_check_llm_response

        messages = [
            {'role': 'system', 'content': "Reasoning: high"},
            {'role': 'user', 'content': (
                "You are a brilliant oncologist with encyclopedic knowledge about cancer and its treatment.\n"
                "Your job is to evaluate whether a patient has any underlying medical conditions that would exclude him or her from a specific clinical trial.\n\n"
                f"Here is an extract of the patient's history:\n{patient_boilerplate}\n"
                f"Here are the exclusion criteria for the trial:\n{trial_boilerplate}\n"
                "Note that the extract was generated by prompting an LLM to determine whether the patient meets specific common exclusion criteria, "
                "such as uncontrolled brain metastases, lack of measurable disease, congestive heart failure, pneumonitis, renal dysfunction, "
                "liver dysfunction, and HIV or hepatitis infection, and to present evidence for whether the patient met the criterion.\n"
                "You should therefore not assume that mention of such condition means the patient has the condition; it may represent the LLM reasoning "
                "about whether the patient has the condition.\n"
                "Based on the extract, you should determine whether the patient clearly meets one of the exclusion criteria for this specific trial.\n"
                "Do not evaluate exclusion criteria other than those listed for this trial.\n"
                "Reason through one exclusion criterion at a time. Generate a numbered list of the criteria as you go. For each one, decide whether the patient clearly "
                "meets the exclusion criteron. If it is not completely clear that the patient meets the exclusion criterion, give the patient the benefit of the doubt, "
                "and err on the side of deciding the patient is not excluded. A description in the patient extract that a condition is mild, low-grade, or resolved is even "
                "more of a reason not to exclude the patient based on that condition.\n"
                'Once you have evaluated all exclusion criteria, answer the question "Is this patient clearly excluded from this trial?" with a one-word "Yes!" or "No!" answer, '
                "based on whether the patient clearly met any of the individual exclusion criteria. It is critical that your final word be either \"Yes!\" or \"No!\", verbatim, and case-sensitive.\n"
                "Make sure to include the exclamation point in your final one-word answer.\n"
                "No introductory text or concluding text after that final answer."
            )},
            {'role': 'assistant', 'content': answer}
        ]

        prompt = tokenizer.apply_chat_template(conversation=messages, tokenize=False)
        prompts.append(prompt)

    return prompts


def main():
    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained('meta-llama/llama-3.2-3B-Instruct')

    print("Loading boilerplate checks data from ../../data/no_phi/boilerplate_checks/final_boilerplate_checks.parquet...")
    boilerplate_checks = pd.read_parquet('../../data/no_phi/boilerplate_checks/final_boilerplate_checks.parquet')
    print(f"Loaded {len(boilerplate_checks)} records")

    print("Generating training prompts...")
    output = boilerplatecheck(boilerplate_checks, tokenizer)

    print("Saving to ../../data/no_phi/oncoreasoning_training_data/boilerplate_checks.parquet...")
    pd.DataFrame(output, columns=['text']).to_parquet('../../data/no_phi/oncoreasoning_training_data/boilerplate_checks.parquet')
    print(f"Done! Saved {len(output)} records")


if __name__ == '__main__':
    main()
